### ISSUE TITLE
Question. Will click/action listeners be saved somehow onSaveInstanceState?

### ISSUE THREAD

**Issue by luckcoolla** [pranavpandey/dynamic-dialogs#2]
1) Will click/action listeners be saved somehow onSaveInstanceState? 
Or should I renew listeners with some methods?

2) how to find dialog that is now shown on the screen? 
With DialogFragment I can use fragmentManager's methods

**Comment by pranavpandey** [comment]
1. It will work similarly like the `AppCompatDialog` but if you are using `DynamicDialogFragment` then, it will save the fragment listeners by calling the `setRetainInstance(true)` in its `onCreate(savedInstanceState)` method.  

2. Like `AppCompatDialogFragment`, you can call `getDialog()` (or `getDynamicDialog()`) method to retrieve the dialog shown by the fragment. 

In background, it uses the default implementation of AndroidX dialogs so, everything will continue to work like before. You just have to replace the `AppCompatDialog` with `DynamicDialog` and `AppCompatDialogFragment` with `DynamicDialogFragment` then, override the necessary methods. For more info, please check the [sample](https://github.com/pranavpandey/dynamic-dialogs/tree/master/sample).

**Comment by pranavpandey** [comment]
Closing it for now. Please feel free to reopen in case of any issues.
